Repository apache/skywalking-nodejs, pull requests merged in 2020-12, with the labels that each got.

#4 withSpanAwait(), HttpPlugin errorer on abort/error
  src/plugins/HttpPlugin.ts
  src/trace/context/ContextManager.ts
Labels: enhancement

#5 [Enhancement] tweaks for better error handling
  src/plugins/HttpPlugin.ts
  src/trace/context/ContextManager.ts
Labels: enhancement

#6 tslib as normal not dev dependancy
  package.json
Labels: bug

#7 Node 10 AsyncLocalStorage and Plugin loader
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  jest.setup.js
  package-lock.json
  src/core/PluginInstaller.ts
  src/plugins/HttpPlugin.ts
  src/trace/context/ContextManager.ts
Labels: core, enhancement

#8 test: set up Node version matrix to test different versions
  .github/workflows/test.yaml
  tests/plugins/common/Dockerfile.agent
  tests/plugins/common/base-compose.yml
Labels: test

#9 [WIP] express plugin, make spans actually work
  src/agent/Buffer.ts
  src/config/AgentConfig.ts
  src/core/PluginInstaller.ts
  src/index.ts
  src/plugins/AxiosPlugin.ts
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  src/trace/Component.ts
  src/trace/context/SpanContext.ts
  src/trace/span/DummySpan.ts
  src/trace/span/EntrySpan.ts
  src/trace/span/ExitSpan.ts
  src/trace/span/Span.ts
  src/trace/span/StackedSpan.ts
  tests/plugins/http/expected.data.yaml
Labels: plugin

#11 chore: update dependencies and polish codes
  package-lock.json
  package.json
  src/agent/protocol/grpc/SegmentObjectAdapter.ts
  src/agent/protocol/grpc/clients/HeartbeatClient.ts
  src/agent/protocol/grpc/clients/TraceReportClient.ts
  src/trace/context/SpanContext.ts
  tests/plugins/http/test.ts
Labels: chore

#12 Init the client twoice,Make sure the config take effect
  src/agent/protocol/grpc/clients/HeartbeatClient.ts
  src/agent/protocol/grpc/clients/TraceReportClient.ts
Labels: bug

#14 Update submodule over https instead of ssh in case of no ssh is configured
  .gitmodules
Labels: bug

#15 Make the contract channels clear
  README.md
Labels: chore

#16 Add changelog for 0.1.0
  CHANGELOG.md
Labels: chore

#17 Polish the readme to clarify the init options
  README.md
Labels: documentation

#18 Go to next version
  README.md
  package.json
Labels: chore

#19 Add documentations about how to release
  README.md
  docs/How-to-release.md
  package-lock.json
  package.json
Labels: documentation
