Repository apache/skywalking-nodejs, pull requests merged in 2021-03, with the labels that each got.

#33 MongoDB first working version
  README.md
  package.json
  src/Tag.ts
  src/config/AgentConfig.ts
  src/plugins/MongoDBPlugin.ts
  src/plugins/MySQLPlugin.ts
  src/plugins/PgPlugin.ts
  tests/plugins/mongodb/client.ts
  tests/plugins/mongodb/docker-compose.yml
  tests/plugins/mongodb/expected.data.yaml
  tests/plugins/mongodb/init/init.js
  tests/plugins/mongodb/server.ts
  tests/plugins/mongodb/test.ts
Labels: plugin

#34 Add AMQPLib plugin (RabbitMQ)
  README.md
  package-lock.json
  package.json
  src/Tag.ts
  src/plugins/AMQPLibPlugin.ts
  src/plugins/MongoDBPlugin.ts
  src/trace/Component.ts
  src/trace/span/Span.ts
  tests/plugins/mongodb/expected.data.yaml
  tests/plugins/pg/client.ts
  tests/plugins/pg/server.ts
Labels: plugin

#36 Fixing async and preparing child entry/exit
  README.md
  src/config/AgentConfig.ts
  src/core/PluginInstaller.ts
  src/plugins/AMQPLibPlugin.ts
  src/plugins/AxiosPlugin.ts
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  src/plugins/MongoDBPlugin.ts
  src/plugins/MySQLPlugin.ts
  src/plugins/PgPlugin.ts
  src/trace/context/Context.ts
  src/trace/context/ContextManager.ts
  src/trace/context/DummyContext.ts
  src/trace/context/SpanContext.ts
  src/trace/span/Span.ts
  tests/plugins/axios/expected.data.yaml
  tests/plugins/express/expected.data.yaml
  tests/plugins/http/expected.data.yaml
  tests/plugins/mongodb/expected.data.yaml
  tests/plugins/mysql/expected.data.yaml
  tests/plugins/pg/expected.data.yaml
Labels: enhancement

#38 Refactor and cleanups
  src/annotations/index.ts
  src/core/SwPlugin.ts
  src/plugins/AMQPLibPlugin.ts
  src/plugins/AxiosPlugin.ts
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  src/plugins/MongoDBPlugin.ts
  src/plugins/MySQLPlugin.ts
  src/plugins/PgPlugin.ts
  src/trace/context/SpanContext.ts
  src/trace/span/Span.ts
  src/trace/span/StackedSpan.ts
  tests/plugins/axios/expected.data.yaml
  tests/plugins/express/expected.data.yaml
Labels: enhancement

#39 HttpClient fixes
  README.md
  src/core/SwPlugin.ts
  src/plugins/HttpPlugin.ts
Labels: enhancement, plugin

#42 express uses http wrap explicitly if http disabled
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  src/trace/span/EntrySpan.ts
Labels: enhancement

#43 chore: draft release notes for 0.2.0
  CHANGELOG.md
  package-lock.json
Labels: chore

#46 BugFix: wrong context during many async spans
  src/trace/context/Context.ts
  src/trace/context/ContextManager.ts
  src/trace/context/DummyContext.ts
  src/trace/context/SpanContext.ts
Labels: bug
