Repository apache/skywalking-nodejs, pull requests merged in 2021-01, with the labels that each got.

#20 Fix bug that some requests of express / axios are not close correctly
  dist/LICENSE
  package-lock.json
  package.json
  src/core/PluginInstaller.ts
  src/core/SwPlugin.ts
  src/plugins/AxiosPlugin.ts
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  src/trace/context/SpanContext.ts
  src/trace/span/Span.ts
  tests/plugins/axios/expected.data.yaml
  tests/plugins/express/expected.data.yaml
  tests/plugins/http/expected.data.yaml
Labels: bug

#21 fix: AxiosPlugin async() / resync()
  src/config/AgentConfig.ts
  src/plugins/AxiosPlugin.ts
  src/plugins/HttpPlugin.ts
  tests/plugins/axios/client.ts
  tests/plugins/axios/expected.data.yaml
  tests/plugins/express/expected.data.yaml
  tests/plugins/http/expected.data.yaml
Labels: bug, plugin

#27 use invalid to check asyncState
  src/trace/context/ContextManager.ts
Labels: bug

#26 added http.method to plugins
  src/Tag.ts
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  tests/plugins/axios/expected.data.yaml
  tests/plugins/express/expected.data.yaml
  tests/plugins/http/expected.data.yaml
Labels: enhancement

#28 Added http protocol to plugins
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  tests/plugins/axios/expected.data.yaml
  tests/plugins/express/expected.data.yaml
  tests/plugins/http/expected.data.yaml
Labels: enhancement
