Repository apache/skywalking-nodejs, pull requests merged in 2022-02, with the labels that each got.

#68 Upgrade dependencies to fix vulnerabilities
  package-lock.json
Labels: dependencies

#69 fix move husky dependency to normal deps
  package.json
Labels: bug

#70 experimental AWS Lambda Function support
  .eslintrc.js
  README.md
  src/agent/protocol/Protocol.ts
  src/agent/protocol/grpc/GrpcProtocol.ts
  src/agent/protocol/grpc/clients/Client.ts
  src/agent/protocol/grpc/clients/HeartbeatClient.ts
  src/agent/protocol/grpc/clients/TraceReportClient.ts
  src/aws/AWSLambdaGatewayAPIHTTP.ts
  src/aws/AWSLambdaGatewayAPIREST.ts
  src/aws/AWSLambdaTriggerPlugin.ts
  src/index.ts
  src/trace/Component.ts
  src/trace/context/ContextManager.ts
Labels: enhancement, plugin

#71 add SW_AWSLAMBDA_FLUSH, fix husky again
  README.md
  package.json
  src/aws/AWSLambdaTriggerPlugin.ts
  src/config/AgentConfig.ts
Labels: bug, enhancement, plugin

#72 fix awaits and SW_AWSLAMBDA_FLUSH default
  src/aws/AWSLambdaTriggerPlugin.ts
  src/config/AgentConfig.ts
Labels: bug

#73 Update IORedis Plugin, fill dbinstance tag as host if condition.select doesn't exist.
  src/plugins/IORedisPlugin.ts
Labels: bug
