Repository apache/skywalking-nodejs, pull requests merged in 2022-10, with the labels that each got.

#94 Ignore no requests if ignoreSuffix is empty
  src/config/AgentConfig.ts
Labels: bug

#97 docs: grammar improvements
  README.md
Labels: chore

#96 fix: entry span url in endponts using Express middleware/router objects
  src/plugins/ExpressPlugin.ts
  tests/plugins/express/client.ts
  tests/plugins/express/expected.data.yaml
  tests/plugins/express/test.ts
Labels: enhancement

#98 chore: use openapi format for endpoint uris
  src/plugins/ExpressPlugin.ts
  src/plugins/HttpPlugin.ts
  tests/plugins/axios/expected.data.yaml
  tests/plugins/express/expected.data.yaml
  tests/plugins/http/expected.data.yaml
  tests/plugins/ioredis/expected.data.yaml
  tests/plugins/mongodb/expected.data.yaml
  tests/plugins/mongoose/expected.data.yaml
  tests/plugins/mysql/expected.data.yaml
  tests/plugins/mysql2/expected.data.yaml
  tests/plugins/pg/expected.data.yaml
Labels: enhancement
