Repository apache/skywalking-nodejs, pull requests merged in 2022-03, with the labels that each got.

#74 Fix mysql2 plugin install error
  src/core/OptionMethods.ts
  src/core/PluginInstaller.ts
  src/core/SwPlugin.ts
  src/plugins/MySQL2Plugin.ts
Labels: bug

#75 Draft release 0.4.0
  CHANGELOG.md
Labels: documentation

#76 Fix wrong command in release doc
  docs/How-to-release.md
Labels: chore

#77 Fix wrong instance properties
  src/agent/protocol/grpc/clients/HeartbeatClient.ts
Labels: bug
